### ISSUE TITLE
Register with name/alias/family/secret

### ISSUE THREAD

**Issue by javajoe1** [craftmaster2190/fgc#2]
Register with a name and alias a family and a secret 
name: so we can see who is playing at the end
alias: so we can see you
family: so we can group you
secret: so you can protect your account -- maybe passoword is still ok, but terminology to indicate it is not super secret

**Comment by craftmaster2190** [comment]
I'm thinking a page that says:
```
Welcome to FGC
Haven't met you before. What's your name?
<Name> <Family>
```
Or if they have logged in before
```
Click on your name (and icon maybe) to login
<User1> <User2> <NewUser>
```

then down at the bottom have options like
```
I have logged in on another device before.
Admin Login
```

Then under the covers, a secret is stored in localStorage that provides the login info. Or just a session is created with this device.
Then when a user returns, they can just click on their name.

If they click, I've logged in on another device before, Send a two factor to the other device, then log them in.

This makes it so that devices are the security measure and no one can cheat and also removes the explicit password.
