### ISSUE TITLE
Add Source Maps

### ISSUE THREAD

**Issue by craftmaster2190** [craftmaster2190/fgc#53]

**Comment by javajoe1** [comment]
It looks like the source maps are in the webpack:// . folder ( selecting ctrl-p on windows can allow you to just type the file)

**Comment by javajoe1** [comment]
So if there is something else required, re-open

**Comment by craftmaster2190** [comment]
Are they still the after `ng build --prod`?

**Comment by javajoe1** [comment]
seems to. The "angular.json" has a "false" for source maps in prod and "tsconfig.json" has it to true, so I am not sure which is needed. I can clean up some of these configs if ya want. 
Also, I think "ng build --prod" and "ng serve" do two different things. I don't think "ng serve" considers the "ng build" output. From the project files, I am not quite clear how you are starting the client in docker/aws. Since you do not have source maps in prod, I am guessing you are not using "ng serve" to start the client in prod, but just loading the index.html from the dist. 
Do you need them in prod? I can work on that
