### ISSUE TITLE
Add spotbugs

### ISSUE THREAD

**Issue by craftmaster2190** [craftmaster2190/fgc#61]

**Comment by javajoe1** [comment]
I did some work around this and it seems the gradle plugin is not quite ready. It will currently generate files in build/reports/spotbugs (main.xml and test.xml) but because the gradle plugin is not working well, there is no html report, or a way to configure what gets ignored and what does not.
You can review the main.xml on or about line 212 and see the bugs that are being generated if you want to tackle it, but I would say, let's hold off till this plugin matures.
There are some reports of workarounds but I did not find them successful. Maybe you have a better understanding.

**Comment by craftmaster2190** [comment]
Instead of using the gradle plugin, let's add a github step after owasp runs to wget the jar and using the cli: https://spotbugs.readthedocs.io/en/stable/running.html
